import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const data=JSON.parse(fs.readFileSync("public/data/courses.json","utf8"));
test("expected curriculum data",()=>{const offered=data.courses.filter(c=>c.meetings.length);assert.equal(new Set(offered.map(c=>c.code)).size,14);assert.equal(offered.length,17);assert.equal(new Set(offered.flatMap(c=>c.meetings.map(m=>`${c.term}:${m.crn}`))).size,127);assert.equal(data.courses.find(c=>c.code==="MS6712").meetings.length,0)});
test("course guide covers the current QAB curriculum without importing old IS6941",()=>{const source=fs.readFileSync("app/course-guide.ts","utf8");const codes=[...new Set(data.courses.map(c=>c.code))];assert.equal(codes.length,15);for(const code of codes)assert.match(source,new RegExp(`\\b${code}:`));assert.doesNotMatch(source,/\bIS6941:/);assert.match(source,/chineseTitle/);assert.match(source,/assessment/);assert.match(source,/coreContent/);assert.match(source,/courseFoundation/);assert.match(source,/60%作业\+40%笔试/);assert.match(source,/高等数学、概率论/)});
test("unrestricted or MSCBDA3 Sections are eligible",()=>{const offered=data.courses.filter(c=>c.meetings.length);const eligible=new Set(offered.flatMap(c=>c.meetings.filter(m=>m.eligibleForProgramme).map(m=>`${c.term}:${m.crn}`)));assert.equal(eligible.size,41);for(const c of offered)for(const m of c.meetings){const restricted=/only for Programme\s*:/i.test(m.registrationRestrictions);const includes=/\bMSCBDA3\b/i.test(m.registrationRestrictions);assert.equal(m.eligibleForProgramme,!restricted||includes);assert.equal(m.eligibilityReason,includes?"mscbda3":restricted?"restricted_other":"open")}assert.equal(offered.flatMap(c=>c.meetings).some(m=>m.eligibilityReason==="open"),false);const aIS5413=data.courses.find(c=>c.term==="A"&&c.code==="IS5413");assert.equal(aIS5413.meetings.some(m=>m.eligibleForProgramme),false);const bIS5413=data.courses.find(c=>c.term==="B"&&c.code==="IS5413");assert.equal(new Set(bIS5413.meetings.filter(m=>m.eligibleForProgramme).map(m=>m.crn)).size,2)});
test("multi-meeting Sections preserve continuation rows",()=>{const a=data.courses.find(c=>c.term==="A"&&c.code==="MS5217");const c04=a.meetings.filter(m=>m.crn==="15211");assert.equal(c04.length,2);assert.ok(c04.some(m=>m.day==="T"&&m.startTime==="15:00"&&m.building==="ICP"&&m.room==="UG-101"));const b=data.courses.find(c=>c.term==="A"&&c.code==="MS5218");const c61=b.meetings.filter(m=>m.crn==="11594");assert.equal(c61.length,2);assert.ok(c61.some(m=>m.day==="T"&&m.startTime==="19:00"&&m.building==="ICP"&&m.room==="G-101"))});
test("all public asset paths remain subpath safe",()=>{const html=fs.readFileSync("out/index.html","utf8");assert.doesNotMatch(html,/(?:src|href)="\/(?!\/)/);assert.match(html,/\.\/assets\//)});
test("published output contains no AIMS sessions or local paths",()=>{for(const f of ["out/index.html","out/data/courses.json"]){const s=fs.readFileSync(f,"utf8");assert.doesNotMatch(s,/\/Users\/|banweb\.cityu\.edu\.hk|session.?id|cookie/i)}});
test("conflict rule uses date intersection, same day, strict time overlap",()=>{const overlap=(a,b)=>a.day===b.day&&Math.max(a.ds,b.ds)<=Math.min(a.de,b.de)&&Math.max(a.ts,b.ts)<Math.min(a.te,b.te);assert.equal(overlap({day:"M",ds:1,de:9,ts:900,te:950},{day:"M",ds:2,de:8,ts:940,te:1000}),true);assert.equal(overlap({day:"M",ds:1,de:2,ts:900,te:950},{day:"M",ds:3,de:4,ts:940,te:1000}),false);assert.equal(overlap({day:"M",ds:1,de:4,ts:900,te:950},{day:"M",ds:1,de:4,ts:950,te:1000}),false)});
