"use client";

import { useEffect, useMemo, useState } from "react";
import { COURSE_GUIDE } from "./course-guide";

type Meeting={crn:string;section:string;credits:number;campus:string;web:string;level:string;available:number;capacity:number;waitlistAvailable:string;startDate:string;endDate:string;day:string;startTime:string;endTime:string;building:string;room:string;instructor:string;medium:string;registrationRestrictions:string;eligibleForProgramme:boolean;eligibilityReason:"open"|"mscbda3"|"restricted_other";meetingIndex:number};
type Course={academicYear:string;term:string;termName:string;code:string;title:string;category:string;credits:number;prerequisites:string[];notes:string;meetings:Meeting[]};
type SelectedSection={course:Course;crn:string;meetings:Meeting[]};
type Data={snapshotDate:string;courses:Course[]};
type Picks=Record<string,Record<string,string>>;
const TERMS=[{id:"A",name:"Semester A"},{id:"B",name:"Semester B"},{id:"S",name:"Summer Term"},{id:"U",name:"未开课"}];
const DAYS:Record<string,string>={M:"周一",T:"周二",W:"周三",R:"周四",F:"周五",S:"周六",U:"周日"};
const CAT:Record<string,string>={programme_core:"Programme Core",stream_core:"QAB Stream Core",stream_elective:"QAB Stream Elective"};
const CATEGORY_COLORS:Record<string,{background:string;foreground:string}>={programme_core:{background:"#d4eee4",foreground:"#164f40"},stream_core:{background:"#e4ddf2",foreground:"#563f75"},stream_elective:{background:"#f3e4c9",foreground:"#795a21"}};
const EMPTY:Picks={A:{},B:{},S:{}};
const mins=(v:string)=>{const [h,m]=v.split(":").map(Number);return h*60+m};
const date=(v:string)=>{const [d,m,y]=v.split("/").map(Number);return new Date(y,m-1,d).getTime()};
const groups=(course:Course)=>[...new Map(course.meetings.map(m=>[m.crn,course.meetings.filter(x=>x.crn===m.crn)])).values()];
const eligibleGroups=(course:Course)=>groups(course).filter(ms=>ms[0].eligibleForProgramme);
const meetingKey=(course:Course,meeting:Meeting)=>`${course.term}:${course.code}:${meeting.crn}:${meeting.meetingIndex}`;

export default function Home(){
 const [data,setData]=useState<Data|null>(null),[term,setTerm]=useState("A"),[query,setQuery]=useState(""),[cat,setCat]=useState("all"),[day,setDay]=useState("all"),[available,setAvailable]=useState(false),[picks,setPicks]=useState<Picks>(EMPTY),[chooser,setChooser]=useState<Course|null>(null),[detail,setDetail]=useState<Course|null>(null),[view,setView]=useState("grid"),[ready,setReady]=useState(false);
 useEffect(()=>{fetch("./data/courses.json").then(r=>r.json()).then(setData);queueMicrotask(()=>{try{const saved=localStorage.getItem("qab-picks-v1");if(saved)setPicks(JSON.parse(saved));const prefs=localStorage.getItem("qab-prefs-v1");if(prefs){const p=JSON.parse(prefs);setTerm(p.term||"A");setView(p.view||"grid")}}catch{/* 本地存储不可用时使用默认设置 */}setReady(true)})},[]);
 useEffect(()=>{if(ready)localStorage.setItem("qab-picks-v1",JSON.stringify(picks))},[picks,ready]);
 useEffect(()=>{if(ready)localStorage.setItem("qab-prefs-v1",JSON.stringify({term,view,query,cat,day,available}))},[term,view,query,cat,day,available,ready]);
 const courses=useMemo(()=>data?.courses||[],[data]);
 const shown=useMemo(()=>courses.filter(c=>c.term===term&&(cat==="all"||c.category===cat)&&(day==="all"||c.meetings.some(m=>m.eligibleForProgramme&&m.day===day))&&(!available||c.meetings.some(m=>m.eligibleForProgramme&&m.available>0))&&(`${c.code} ${c.title}`.toLowerCase().includes(query.toLowerCase()))),[courses,term,cat,day,available,query]);
 const selected=useMemo(()=>Object.entries(picks).flatMap(([t,ps])=>Object.entries(ps).map(([code,crn])=>{const c=courses.find(x=>x.term===t&&x.code===code),meetings=c?.meetings.filter(x=>x.crn===crn&&x.eligibleForProgramme)||[];return c&&meetings.length?{course:c,crn,meetings}:null}).filter(Boolean) as SelectedSection[]),[picks,courses]);
 const termSelected=selected.filter(x=>x.course.term===term);
 const termMeetings=termSelected.flatMap(x=>x.meetings.map(meeting=>({course:x.course,meeting})));
 const conflictKeys=new Set<string>(); const conflicts:{a:string,b:string,time:string}[]=[];
 for(let i=0;i<termMeetings.length;i++)for(let j=i+1;j<termMeetings.length;j++){const a=termMeetings[i],b=termMeetings[j];if(a.course.code===b.course.code&&a.meeting.crn===b.meeting.crn)continue;if(a.meeting.day===b.meeting.day&&Math.max(date(a.meeting.startDate),date(b.meeting.startDate))<=Math.min(date(a.meeting.endDate),date(b.meeting.endDate))&&Math.max(mins(a.meeting.startTime),mins(b.meeting.startTime))<Math.min(mins(a.meeting.endTime),mins(b.meeting.endTime))){conflictKeys.add(meetingKey(a.course,a.meeting));conflictKeys.add(meetingKey(b.course,b.meeting));const start=Math.max(mins(a.meeting.startTime),mins(b.meeting.startTime)),end=Math.min(mins(a.meeting.endTime),mins(b.meeting.endTime)),clock=(v:number)=>`${String(Math.floor(v/60)).padStart(2,"0")}:${String(v%60).padStart(2,"0")}`;conflicts.push({a:`${a.course.code} ${a.meeting.section}`,b:`${b.course.code} ${b.meeting.section}`,time:`${DAYS[a.meeting.day]} ${clock(start)}–${clock(end)}`})}}
 const unique=[...new Map(selected.map(x=>[x.course.code,x.course])).values()]; const credits=unique.reduce((s,c)=>s+c.credits,0),pc=unique.filter(c=>c.category==="programme_core"),sc=unique.filter(c=>c.category==="stream_core"),el=unique.filter(c=>c.category==="stream_elective");
 const prereqWarnings=selected.filter(x=>x.course.prerequisites.length&&!x.course.prerequisites.some(p=>unique.some(c=>c.code===p))).map(x=>`${x.course.code}：建议先修 ${x.course.prerequisites.join(" 或 ")}`);
 function choose(c:Course,m:Meeting){if(!m.eligibleForProgramme){alert("该 Section 明确只限其他 Programme，不能加入课表。");return}const duplicate=Object.entries(picks).some(([t,p])=>t!==c.term&&p[c.code]);if(duplicate){alert(`${c.code} 已在另一学期选择。为避免重复计算，不能再次加入。`);return}setPicks(p=>({...p,[c.term]:{...p[c.term], [c.code]:m.crn}}));setChooser(null)}
 function clear(current:boolean){if(confirm(current?"确定清空当前学期的全部选择？":"确定清空三个学期的全部选择？"))setPicks(p=>current?({...p,[term]:{}}):EMPTY)}
 if(!data)return <main className="loading">正在整理课程数据…</main>;
 return <>
  <header className="hero"><div className="hero-inner"><div className="eyebrow">CITY UNIVERSITY OF HONG KONG · MSc BDA</div><h1>CityU BDA <span>QAB 选课板</span></h1><p>把三个学期放在一张图里，选班次、查冲突、算学分。</p><div className="meta"><b>2026/27</b><b>Full-time</b><b>QAB Stream</b><span>数据快照：2026年8月13日</span></div><div className="notice">非官方网站，仅供课表规划。名额与安排并非实时，最终信息以 CityU AIMS 为准。</div></div></header>
  <nav className="term-tabs" aria-label="学期">{TERMS.map(t=><button key={t.id} className={term===t.id?"active":""} onClick={()=>setTerm(t.id)}>{t.name}<small>{courses.filter(c=>c.term===t.id).length} 门</small></button>)}</nav>
  <main className="shell">
   <section className="progress" aria-label="培养方案进度"><div><small>已选课程</small><strong>{unique.length}<i> / 通常 10</i></strong></div><div><small>总学分</small><strong>{credits}<i> / 30</i></strong></div><div><small>Programme Core</small><strong>{pc.reduce((s,c)=>s+c.credits,0)}<i> / 12</i></strong></div><div><small>Stream Core</small><strong>{sc.reduce((s,c)=>s+c.credits,0)}<i> / 3</i></strong></div><div><small>QAB 选修</small><strong>{el.reduce((s,c)=>s+c.credits,0)}<i> / ≥12</i></strong></div><div className="progress-note">{credits>=30&&el.reduce((s,c)=>s+c.credits,0)>=12?"已达到本工具可核对的学分门槛":"距离 30 学分还差 "+Math.max(0,30-credits)+" 学分"}<small>第一版只统计QAB课程；其他获批CB选修请自行核对。</small></div></section>
   <ProgrammeOverview/>
   {(conflicts.length>0||prereqWarnings.length>0)&&<section className="alerts">{conflicts.map((x,i)=><p className="danger" key={i}>时间冲突：{x.a} ↔ {x.b} · {x.time}</p>)}{prereqWarnings.map((x,i)=><p className="warn" key={i}>先修提示：{x}。仍可选择，请到 AIMS / Course Catalogue 确认资格。</p>)}</section>}
   {term!=="U"&&<section className="schedule-section"><div className="section-head"><div><span className="kicker">MY WEEK</span><h2>{TERMS.find(x=>x.id===term)?.name} 每周课表</h2></div><div className="actions"><button onClick={()=>setView(view==="grid"?"list":"grid")}>{view==="grid"?"按天列表":"时间网格"}</button><button className="quiet" onClick={()=>clear(true)}>清空本学期</button></div></div><div className="schedule-legend" aria-label="课表颜色说明"><span className="programme"><i/>Programme Core</span><span className="stream"><i/>QAB Stream Core</span><span className="elective"><i/>QAB Stream Elective</span><span className="conflict-key"><i/>时间冲突</span></div>{termSelected.length===0?<div className="empty">还没有加入课程。请从下方课程卡选择具体 Section。</div>:view==="list"?<div className="day-list">{"MTWRFS".split("").map(d=><div key={d}><h3>{DAYS[d]}</h3>{termMeetings.filter(x=>x.meeting.day===d).map(x=><ClassBlock key={meetingKey(x.course,x.meeting)} x={x} danger={conflictKeys.has(meetingKey(x.course,x.meeting))} onOpen={()=>setDetail(x.course)}/>)}</div>)}</div>:<Timetable items={termMeetings} conflictKeys={conflictKeys} onOpen={setDetail}/>}</section>}
   <section className="catalog"><div className="section-head"><div><span className="kicker">COURSE CATALOGUE</span><h2>{term==="U"?"培养方案内未开课课程":"浏览本学期课程"}</h2></div><span>{shown.length} 门课程</span></div>
    <div className="filters"><label><span>搜索</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="课程代码或英文名称"/></label><label><span>分类</span><select value={cat} onChange={e=>setCat(e.target.value)}><option value="all">全部分类</option>{Object.entries(CAT).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span>上课星期</span><select value={day} onChange={e=>setDay(e.target.value)}><option value="all">全部星期</option>{Object.entries(DAYS).slice(0,6).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="check"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/><span>有可用班次</span></label></div>
    <div className="eligibility-note"><b>MSCBDA3 选班规则</b><span>未注明 “only for Programme” 的公开班次可以选择；若写有 Programme 限制，则名单必须包含 MSCBDA3。当前快照所有班次都有 Programme 限制，因此目前可选的仍是 41 个 MSCBDA3 班次。</span></div>
    <div className="cards">{shown.map(c=>{const sections=eligibleGroups(c),primary=sections.map(s=>s[0]),allSections=groups(c),picked=sections.some(ms=>ms[0].crn===picks[c.term]?.[c.code]),guide=COURSE_GUIDE[c.code];return <article className="course-card" key={c.term+c.code}><div className="card-top"><span className={`tag ${c.category}`}>{CAT[c.category]}</span><span>{c.credits} 学分</span></div><h3>{c.code}</h3><p className="title">{c.title}</p>{guide&&<><p className="cn-title">{guide.chineseTitle}</p><p className="card-focus">{guide.coreContent}</p><div className="tool-tags">{guide.tools.map(x=><span key={x}>{x}</span>)}</div></>}{c.meetings.length?<><p className="summary">{sections.length?[...new Set(sections.flat().map(m=>`${DAYS[m.day]} ${m.startTime}`))].slice(0,3).join(" · "):"本学期没有 MSCBDA3 专属班次"}</p><div className="capacity"><span>{sections.length} 个可选 Section</span><span>{allSections.length} 个 AIMS 班次</span>{sections.length>0&&<span>{primary.reduce((s,m)=>s+m.available,0)} / {primary.reduce((s,m)=>s+m.capacity,0)} 名额快照</span>}</div></>:<p className="unavailable">属于2026/27 QAB培养方案，但本学年未查到实际开课班次。</p>}<div className="card-actions"><button onClick={()=>setDetail(c)}>查看详情</button><button className="primary" disabled={!sections.length} onClick={()=>setChooser(c)}>{picked?"切换 Section":sections.length?"加入课表":"无可选班次"}</button></div></article>})}</div>
   </section>
   <GuidePanel/>
   <section className="privacy"><h2>关于数据与隐私</h2><div><p>这是非官方学生工具。数据来自 CityU AIMS Master Class Schedule 的保存页面，快照日期为 2026年8月13日。教师、时间、地点、班次、容量、余位和注册状态均可能变化，最终以 CityU AIMS 为准。</p><p>本站不会连接 AIMS，也不会提交正式选课；不收集姓名、学号、账号或个人课表。你的选择只保存在当前浏览器中，不会上传服务器。</p></div><button className="quiet" onClick={()=>clear(false)}>清空全部课表</button></section>
  </main>
  {chooser&&<Modal title={`选择 ${chooser.code} Section`} close={()=>setChooser(null)}><p className="snapshot">显示未注明 Programme 限制的公开班次，以及限制名单包含 MSCBDA3 的班次；每个 Section 会同时加入全部上课时段。名额为 2026年8月13日快照，并非实时名额。</p><div className="section-list">{eligibleGroups(chooser).map(ms=>{const m=ms[0];return <button key={m.crn} className={picks[chooser.term]?.[chooser.code]===m.crn?"selected":""} onClick={()=>choose(chooser,m)}><b>{m.section}</b><span>CRN {m.crn}<br/>{ms.map(x=><i key={x.meetingIndex}>{DAYS[x.day]} {x.startTime}–{x.endTime} · {x.building} {x.room}<br/></i>)}</span><span>{m.instructor||"教师待定"}</span><em>{m.available}/{m.capacity} available</em></button>})}</div></Modal>}
  {detail&&<Modal title={`${detail.code} · ${detail.title}`} close={()=>setDetail(null)}><CourseDetail course={detail}/></Modal>}
 </>
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==="Escape"&&close();addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[close]);return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button aria-label="关闭" onClick={close}>×</button></div>{children}</div></div>}
function ProgrammeOverview(){return <section className="programme-overview"><div className="section-head"><div><span className="kicker">PROGRAMME OVERVIEW</span><h2>QAB 课程构成</h2></div><span className="overview-total">一年全日制 · 30 学分 · 英文授课</span></div><p className="overview-intro">当前选课板按 2026/27 QAB 培养方案计算：先完成 15 学分核心课程，再修满 15 学分选修；其中至少 12 学分来自 QAB Stream Elective。</p><div className="credit-map"><article className="core"><strong>12</strong><div><b>Programme Core</b><p>IS5413 · IS6335 · MS5217 · MS6711</p></div></article><span>+</span><article className="stream"><strong>3</strong><div><b>QAB Stream Core</b><p>MS5218</p></div></article><span>+</span><article className="elective"><strong>15</strong><div><b>Electives</b><p>至少 12 学分 QAB 选修；其余最多 3 学分可为获批 CB 选修</p></div></article><span>=</span><b className="credit-total">30</b></div></section>}
function GuidePanel(){return <section className="guide"><div className="section-head"><div><span className="kicker">SHARED GUIDE · INTEGRATED</span><h2>网传课程指导已经加入</h2></div><span className="guide-badge">历史经验参考</span></div><p className="guide-intro">课程卡现在会显示中文名称、核心学习内容和主要工具；点开“查看详情”可在独立区域查看 PDF 对应的【考核方式】【核心内容】【课程基础】。下列方法也来自材料前半部分的 QAB 学习建议。</p><div className="guide-grid"><article><b>学习路径</b><p>先打好统计分析、线性模型与数据管理基础，再进入数据挖掘、预测建模、风险或金融建模。</p></article><article><b>数学与统计</b><p>复习描述统计、概率、微积分和线性代数，为 MS5217、MS5218 及进阶建模课做准备。</p></article><article><b>编程与工具</b><p>补齐 Python 基础语法、NumPy、Pandas 和 SQL；根据课程方向预习 R、Tableau 与 Excel。</p></article></div><p className="guide-source">来源：同学提供的网传《QAB选课指导》。材料中的课程设置、学期及考核可能属于往届，仅作经验参考；最终以 AIMS、Course Catalogue、当年课程大纲和 Programme Office 为准。</p></section>}
function CourseDetail({course:c}:{course:Course}){const guide=COURSE_GUIDE[c.code];return <div className="detail"><div className="detail-meta"><span className={`tag ${c.category}`}>{CAT[c.category]}</span><b>{c.credits} 学分</b><b>{c.termName}</b></div>{guide&&<section className="course-reference"><div className="reference-head"><div><span className="reference-label">网传《QAB选课指导》课程档案</span><h3>{guide.chineseTitle}</h3></div><span className="reference-warning">非官方 · 历史参考</span></div><div className="pdf-fields"><article><b>考核方式</b><p>{guide.assessment}</p></article><article><b>核心内容</b><p>{guide.coreContent}</p></article><article><b>课程基础</b><p>{guide.courseFoundation}</p></article></div><small>以上三项按同学提供的 PDF 表格整理；考核比例、教学内容和基础要求可能随学期调整，请以任课教师公布的当年课程大纲及 Course Catalogue 为准。</small></section>}{c.prerequisites.length>0&&<p className="warn">先修提示：{c.prerequisites.join(" 或 ")}。请以 AIMS / Course Catalogue 为准。</p>}{c.notes&&<p>{c.notes}</p>}<p className="snapshot">同一 Section 的全部上课时段均列在一起。绿色为可选班次（公开或包含 MSCBDA3）；灰色为明确只限其他 Programme。名额为 2026年8月13日快照，并非实时名额。</p>{c.meetings.length?<div className="detail-table"><table><thead><tr><th>Section / CRN</th><th>全部日期与时间</th><th>地点 / 教师</th><th>状态</th></tr></thead><tbody>{groups(c).map(ms=>{const m=ms[0];return <tr className={m.eligibleForProgramme?"eligible-row":"ineligible-row"} key={m.crn}><td><b>{m.section}</b><br/>CRN {m.crn}<br/><span className={`eligibility ${m.eligibleForProgramme?"yes":"no"}`}>{m.eligibilityReason==="open"?"公开班次，可选":m.eligibilityReason==="mscbda3"?"MSCBDA3 可选":"只限其他 Programme"}</span></td><td>{ms.map(x=><div className="meeting-line" key={x.meetingIndex}>{x.startDate}–{x.endDate}<br/><b>{DAYS[x.day]} {x.startTime}–{x.endTime}</b></div>)}</td><td>{ms.map(x=><div className="meeting-line" key={x.meetingIndex}><b>{x.building} {x.room}</b><br/>{x.instructor||"待定"} · {x.medium}</div>)}</td><td>WEB {m.web}<br/>{m.available}/{m.capacity} available<br/>Waitlist {m.waitlistAvailable}{m.registrationRestrictions?<small>{m.registrationRestrictions}</small>:<small>没有 Programme 限制</small>}</td></tr>})}</tbody></table></div>:<p className="unavailable">属于2026/27 QAB培养方案，但本学年未查到实际开课班次；不能加入课表，也不计入学分。</p>}</div>}
function ClassBlock({x,danger,onOpen}:{x:{course:Course,meeting:Meeting},danger:boolean,onOpen:()=>void}){const colors=CATEGORY_COLORS[x.course.category];return <button className={`class-block ${danger?"conflict":""}`} style={{borderLeftColor:colors.foreground,background:colors.background,color:colors.foreground}} onClick={onOpen}><b>{x.course.code} · {x.meeting.section}</b><span>{x.meeting.startTime}–{x.meeting.endTime}</span><span>{x.meeting.building} {x.meeting.room}</span></button>}
function Timetable({items,conflictKeys,onOpen}:{items:{course:Course,meeting:Meeting}[],conflictKeys:Set<string>,onOpen:(c:Course)=>void}){return <div className="timetable"><div className="time-col">{[9,11,13,15,17,19,21].map(h=><span key={h}>{String(h).padStart(2,"0")}:00</span>)}</div>{"MTWRFS".split("").map(d=><div className="day-col" key={d}><h3>{DAYS[d]}</h3><div className="day-canvas">{items.filter(x=>x.meeting.day===d).map(x=>{const colors=CATEGORY_COLORS[x.course.category];return <button key={meetingKey(x.course,x.meeting)} className={`grid-block ${conflictKeys.has(meetingKey(x.course,x.meeting))?"conflict":""}`} style={{top:`${(mins(x.meeting.startTime)-540)/780*100}%`,height:`${Math.max(8,(mins(x.meeting.endTime)-mins(x.meeting.startTime))/780*100)}%`,background:colors.background,color:colors.foreground}} onClick={()=>onOpen(x.course)}><b>{x.course.code}</b><span>{x.meeting.section}</span><small>{x.meeting.startTime}<br/>{x.meeting.building} {x.meeting.room}</small></button>})}</div></div>)}</div>}
